"""
Configuration file for Peer Effects and Adoption Analysis
==========================================================

This module provides centralized path management and configuration settings
for all analysis scripts. Update BASE_DIR to match your local setup.

Directory Structure:
    1_Data/
        Raw/        - Original data files organized by source
        Cleaned/    - Processed datasets (generated by preparation scripts)
        Weights/    - Spatial weight matrices (generated by preparation scripts)
    2_Scripts/      - All Python scripts
    3_Output/
        Tables/     - Regression results and summary statistics
        Figures/    - Plots and visualizations
        Logs/       - Execution logs
    4_Documentation/ - Analysis memos and documentation

Author: [Your Name]
Last Updated: November 30, 2025
"""

from pathlib import Path

# =============================================================================
# Base Directory Configuration
# =============================================================================

# Base directory - update this to match your local setup
BASE_DIR = Path(r"c:\BC PhD\Research\Peer-Effects and Adoption")

# =============================================================================
# Data Directories
# =============================================================================

# Main data folders
DATA_DIR = BASE_DIR / "1_Data"
RAW_DIR = DATA_DIR / "Raw"
CLEANED_DIR = DATA_DIR / "Cleaned"
WEIGHTS_DIR = DATA_DIR / "Weights"

# Raw data subfolders
RAW_SPATIAL_DIR = RAW_DIR / "Spatial"
RAW_CLIMATE_DIR = RAW_DIR / "Climate"
RAW_WRI_DIR = RAW_DIR / "WRI"
RAW_POLITICAL_DIR = RAW_DIR / "Political"
RAW_OTHER_DIR = RAW_DIR / "Other"

# Weight matrix subfolders
CLIMATE_WEIGHTS_DIR = WEIGHTS_DIR / "climate_weights"
GEO_WEIGHTS_DIR = WEIGHTS_DIR / "geo_weights"

# =============================================================================
# Raw Data Files
# =============================================================================

# Spatial data
SCHOOL_DISTRICTS_SHP = RAW_SPATIAL_DIR / "EDGE_SCHOOLDISTRICT_TL21_SY2021" / "schooldistrict_sy2021_tl21.shp"

# Climate data
PRISM_PRECIP_FILE = RAW_CLIMATE_DIR / "Climate and Terrain" / "prism_ppt_us_30s_202001_avg_30y" / "prism_ppt_us_30s_202001_avg_30y.tif"
PRISM_TMIN_FILE = RAW_CLIMATE_DIR / "Climate and Terrain" / "prism_tmin_us_30s_202001_avg_30y" / "prism_tmin_us_30s_202001_avg_30y.tif"

# WRI data
WRI_EXCEL_FILE = RAW_WRI_DIR / "ESB_adoption_dataset_v9_update_june_2025.xlsx"
WRI_CSV_FILE = RAW_WRI_DIR / "wri_data.csv"

# EPA Clean School Bus Program data
ADOPTION_REBATES_FILE = RAW_WRI_DIR / "CSB_Rebates.xlsx"
ADOPTION_GRANTS_FILE = RAW_WRI_DIR / "CSB_Grants.xlsx"
APPLICANT_FILE = RAW_WRI_DIR / "CSBP Applicants waitlisted and rejected_11.18.25.xlsx"

# Political data
POLITICAL_COUNTY_PRES_FILE = RAW_POLITICAL_DIR / "dataverse_files" / "countypres_2000-2024.csv"

# Other data
PROGRAM_CALENDAR_FILE = RAW_OTHER_DIR / "program_calendar.csv"
CHARGING_STATIONS_FILE = RAW_OTHER_DIR / "alt_fuel_stations_historical_day (Jan 1 2020).csv"
ZIP_COUNTY_FILE = RAW_OTHER_DIR / "ZIP_COUNTY_122020.xlsx"

# =============================================================================
# Cleaned Data Files
# =============================================================================

# Main analysis datasets
ESB_MASTER_DATA = CLEANED_DIR / "esb_master_data_for_regression.csv"
ESB_FULL_ANALYSIS = CLEANED_DIR / "esb_full_analysis_dataset.csv"
CHARTER_FLAGS = CLEANED_DIR / "charter_flags.csv"
LEA_QUARTER_PANEL = CLEANED_DIR / "lea_quarter_panel.csv"
LEA_QUARTER_PANEL_WITH_PEERS = CLEANED_DIR / "lea_quarter_panel_with_peers.csv"
LEA_STAGE_IMPUTATION = CLEANED_DIR / "lea_stage_imputation.csv"
LEA_PEER_VARS = CLEANED_DIR / "lea_peer_vars.csv"

# Climate similarity data
CLIMATE_SIMILARITY_DATA = CLEANED_DIR / "district_climate_normals.csv"

# =============================================================================
# Output Directories
# =============================================================================

OUTPUT_DIR = BASE_DIR / "3_Output"
TABLES_DIR = OUTPUT_DIR / "Tables"
FIGURES_DIR = OUTPUT_DIR / "Figures"
LOGS_DIR = OUTPUT_DIR / "Logs"

# =============================================================================
# Analysis Configuration
# =============================================================================

# Climate-based KNN specifications
CLIMATE_KNN_VALUES = [4, 6, 8, 10, 12, 15, 20]

# Geographic distance bands (in miles)
GEO_DISTANCE_BANDS = [10, 25, 50, 75, 100, 150]

# Regression specifications
INCLUDE_STATE_FE = True
INCLUDE_YEAR_FE = True

# Random seed for reproducibility
RANDOM_SEED = 42

# =============================================================================
# Utility Functions
# =============================================================================

def ensure_dirs_exist():
    """Create all necessary directories if they don't exist."""
    dirs_to_create = [
        CLEANED_DIR,
        WEIGHTS_DIR,
        CLIMATE_WEIGHTS_DIR,
        GEO_WEIGHTS_DIR,
        TABLES_DIR,
        FIGURES_DIR,
        LOGS_DIR
    ]
    
    for dir_path in dirs_to_create:
        dir_path.mkdir(parents=True, exist_ok=True)
    
    print("All necessary directories created/verified.")

def get_climate_weight_file(k):
    """
    Get path to climate-based KNN weight file.
    
    Parameters
    ----------
    k : int
        Number of nearest neighbors
        
    Returns
    -------
    Path
        Full path to weight file
    """
    return CLIMATE_WEIGHTS_DIR / f"climate_knn_k{k}.pkl"

def get_geo_weight_file(distance):
    """
    Get path to geographic distance-based weight file.
    
    Parameters
    ----------
    distance : int
        Distance threshold in miles
        
    Returns
    -------
    Path
        Full path to weight file
    """
    return GEO_WEIGHTS_DIR / f"geo_distance_{distance}mi.pkl"

# =============================================================================
# Main
# =============================================================================

if __name__ == "__main__":
    # Verify base directory exists
    if not BASE_DIR.exists():
        print(f"WARNING: Base directory does not exist: {BASE_DIR}")
        print("Please update BASE_DIR in config.py")
    else:
        print(f"Base directory: {BASE_DIR}")
        print(f"Raw data directory: {RAW_DIR}")
        print(f"Cleaned data directory: {CLEANED_DIR}")
        print(f"Output directory: {OUTPUT_DIR}")
        
        # Create necessary directories
        ensure_dirs_exist()
